/*

 MEOWSPRITE.H

 Include File.

 Info:
  Form                 : Each tile separate.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __MeowSprite_h_INCLUDE
#define __MeowSprite_h_INCLUDE

/* Bank of tiles. */
#define MeowSpriteBank 0

extern const unsigned char MeowSpriteTLE0[];
extern UWORD blob_pallette[4];

#endif

/* End of MEOWSPRITE.H */
