/*

 MEOWSPRITE.C

 Tile Source File.

 Info:
  Form                 : Each tile separate.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/
#include <gb/gb.h>

const UWORD blob_pallette[4]={3839,32328,223,31248};
const unsigned char MeowSpriteTLE0[] =
{
  0x3C,0x00,0x7E,0x3C,0xD7,0x7C,0xFF,0x7E,
  0xFF,0x7E,0xFE,0x7C,0x7C,0x38,0x38,0x00
};

/* End of MEOWSPRITE.C */
