//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_gorbySleeping_H
#define METASPRITE_gorbySleeping_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define gorbySleeping_TILE_ORIGIN 0
#define gorbySleeping_TILE_W 8
#define gorbySleeping_TILE_H 16
#define gorbySleeping_WIDTH 16
#define gorbySleeping_HEIGHT 16
#define gorbySleeping_TILE_COUNT 16
#define gorbySleeping_PALETTE_COUNT 1
#define gorbySleeping_COLORS_PER_PALETTE 4
#define gorbySleeping_TOTAL_COLORS 4
#define gorbySleeping_PIVOT_X 8
#define gorbySleeping_PIVOT_Y 8
#define gorbySleeping_PIVOT_W 16
#define gorbySleeping_PIVOT_H 16
extern const metasprite_t* const gorbySleeping_metasprites[5];

BANKREF_EXTERN(gorbySleeping)

extern const palette_color_t gorbySleeping_palettes[4];
extern const uint8_t gorbySleeping_tiles[256];

#endif
