//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_splashscreen3_H
#define METASPRITE_splashscreen3_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define splashscreen3_TILE_ORIGIN 0
#define splashscreen3_TILE_W 8
#define splashscreen3_TILE_H 8
#define splashscreen3_WIDTH 160
#define splashscreen3_HEIGHT 144
#define splashscreen3_TILE_COUNT 179
#define splashscreen3_PALETTE_COUNT 8
#define splashscreen3_COLORS_PER_PALETTE 4
#define splashscreen3_TOTAL_COLORS 32
#define splashscreen3_MAP_ATTRIBUTES splashscreen3_map_attributes
#define splashscreen3_MAP_ATTRIBUTES_WIDTH 20
#define splashscreen3_MAP_ATTRIBUTES_HEIGHT 18
#define splashscreen3_MAP_ATTRIBUTES_PACKED_WIDTH 20
#define splashscreen3_MAP_ATTRIBUTES_PACKED_HEIGHT 18
extern const unsigned char splashscreen3_map[360];
extern const unsigned char splashscreen3_map_attributes[360];

BANKREF_EXTERN(splashscreen3)

extern const palette_color_t splashscreen3_palettes[32];
extern const uint8_t splashscreen3_tiles[2864];

#endif
