//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_TheAgeOfGorby_H
#define METASPRITE_TheAgeOfGorby_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define TheAgeOfGorby_TILE_ORIGIN 0
#define TheAgeOfGorby_TILE_W 8
#define TheAgeOfGorby_TILE_H 8
#define TheAgeOfGorby_WIDTH 160
#define TheAgeOfGorby_HEIGHT 144
#define TheAgeOfGorby_TILE_COUNT 245
#define TheAgeOfGorby_PALETTE_COUNT 5
#define TheAgeOfGorby_COLORS_PER_PALETTE 4
#define TheAgeOfGorby_TOTAL_COLORS 20
#define TheAgeOfGorby_MAP_ATTRIBUTES TheAgeOfGorby_map_attributes
#define TheAgeOfGorby_MAP_ATTRIBUTES_WIDTH 20
#define TheAgeOfGorby_MAP_ATTRIBUTES_HEIGHT 18
#define TheAgeOfGorby_MAP_ATTRIBUTES_PACKED_WIDTH 20
#define TheAgeOfGorby_MAP_ATTRIBUTES_PACKED_HEIGHT 18
extern const unsigned char TheAgeOfGorby_map[360];
extern const unsigned char TheAgeOfGorby_map_attributes[360];

BANKREF_EXTERN(TheAgeOfGorby)

extern const palette_color_t TheAgeOfGorby_palettes[20];
extern const uint8_t TheAgeOfGorby_tiles[3920];

#endif
