//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_WalkingGorb_H
#define METASPRITE_WalkingGorb_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define WalkingGorb_TILE_ORIGIN 0
#define WalkingGorb_TILE_W 8
#define WalkingGorb_TILE_H 16
#define WalkingGorb_WIDTH 16
#define WalkingGorb_HEIGHT 16
#define WalkingGorb_TILE_COUNT 30
#define WalkingGorb_PALETTE_COUNT 1
#define WalkingGorb_COLORS_PER_PALETTE 4
#define WalkingGorb_TOTAL_COLORS 4
#define WalkingGorb_PIVOT_X 8
#define WalkingGorb_PIVOT_Y 8
#define WalkingGorb_PIVOT_W 16
#define WalkingGorb_PIVOT_H 16
extern const metasprite_t* const WalkingGorb_metasprites[10];

BANKREF_EXTERN(WalkingGorb)

extern const palette_color_t WalkingGorb_palettes[4];
extern const uint8_t WalkingGorb_tiles[480];

#endif
