//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_WalkingGorbUp_H
#define METASPRITE_WalkingGorbUp_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define WalkingGorbUp_TILE_ORIGIN 0
#define WalkingGorbUp_TILE_W 8
#define WalkingGorbUp_TILE_H 16
#define WalkingGorbUp_WIDTH 16
#define WalkingGorbUp_HEIGHT 16
#define WalkingGorbUp_TILE_COUNT 38
#define WalkingGorbUp_PALETTE_COUNT 1
#define WalkingGorbUp_COLORS_PER_PALETTE 4
#define WalkingGorbUp_TOTAL_COLORS 4
#define WalkingGorbUp_PIVOT_X 8
#define WalkingGorbUp_PIVOT_Y 8
#define WalkingGorbUp_PIVOT_W 16
#define WalkingGorbUp_PIVOT_H 16
extern const metasprite_t* const WalkingGorbUp_metasprites[10];

BANKREF_EXTERN(WalkingGorbUp)

extern const palette_color_t WalkingGorbUp_palettes[4];
extern const uint8_t WalkingGorbUp_tiles[608];

#endif
