//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_WalkingGorbDown_H
#define METASPRITE_WalkingGorbDown_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define WalkingGorbDown_TILE_ORIGIN 0
#define WalkingGorbDown_TILE_W 8
#define WalkingGorbDown_TILE_H 16
#define WalkingGorbDown_WIDTH 16
#define WalkingGorbDown_HEIGHT 16
#define WalkingGorbDown_TILE_COUNT 40
#define WalkingGorbDown_PALETTE_COUNT 1
#define WalkingGorbDown_COLORS_PER_PALETTE 4
#define WalkingGorbDown_TOTAL_COLORS 4
#define WalkingGorbDown_PIVOT_X 8
#define WalkingGorbDown_PIVOT_Y 8
#define WalkingGorbDown_PIVOT_W 16
#define WalkingGorbDown_PIVOT_H 16
extern const metasprite_t* const WalkingGorbDown_metasprites[10];

BANKREF_EXTERN(WalkingGorbDown)

extern const palette_color_t WalkingGorbDown_palettes[4];
extern const uint8_t WalkingGorbDown_tiles[640];

#endif
