//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_splashscreen2_H
#define METASPRITE_splashscreen2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define splashscreen2_TILE_ORIGIN 0
#define splashscreen2_TILE_W 8
#define splashscreen2_TILE_H 8
#define splashscreen2_WIDTH 160
#define splashscreen2_HEIGHT 144
#define splashscreen2_TILE_COUNT 181
#define splashscreen2_PALETTE_COUNT 8
#define splashscreen2_COLORS_PER_PALETTE 4
#define splashscreen2_TOTAL_COLORS 32
#define splashscreen2_MAP_ATTRIBUTES splashscreen2_map_attributes
#define splashscreen2_MAP_ATTRIBUTES_WIDTH 20
#define splashscreen2_MAP_ATTRIBUTES_HEIGHT 18
#define splashscreen2_MAP_ATTRIBUTES_PACKED_WIDTH 20
#define splashscreen2_MAP_ATTRIBUTES_PACKED_HEIGHT 18
extern const unsigned char splashscreen2_map[360];
extern const unsigned char splashscreen2_map_attributes[360];

BANKREF_EXTERN(splashscreen2)

extern const palette_color_t splashscreen2_palettes[32];
extern const uint8_t splashscreen2_tiles[2896];

#endif
