/*

 MEOWSPRITE2.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char MeowSprite2[] =
{
  0x3C,0x00,0x7E,0x3C,0xD7,0x7C,0xFF,0x7E,
  0xFF,0x7E,0xFE,0x7C,0x7C,0x38,0x38,0x00
};

/* End of MEOWSPRITE2.C */
