/*

 MEOWSPRITE.H

 Include File.

 Info:
  Form                 : Each tile separate.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __MeowSprite_h_INCLUDE
#define __MeowSprite_h_INCLUDE

/* Bank of tiles. */
#define MeowSpriteBank 0

/* Super Gameboy palette 0 */
#define MeowSpriteSGBPal0c0 6076
#define MeowSpriteSGBPal0c1 8935
#define MeowSpriteSGBPal0c2 6596
#define MeowSpriteSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define MeowSpriteSGBPal1c0 6076
#define MeowSpriteSGBPal1c1 8935
#define MeowSpriteSGBPal1c2 6596
#define MeowSpriteSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define MeowSpriteSGBPal2c0 6076
#define MeowSpriteSGBPal2c1 8935
#define MeowSpriteSGBPal2c2 6596
#define MeowSpriteSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define MeowSpriteSGBPal3c0 6076
#define MeowSpriteSGBPal3c1 8935
#define MeowSpriteSGBPal3c2 6596
#define MeowSpriteSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define MeowSpriteCGBPal0c0 6076
#define MeowSpriteCGBPal0c1 8935
#define MeowSpriteCGBPal0c2 6596
#define MeowSpriteCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define MeowSpriteCGBPal1c0 3839
#define MeowSpriteCGBPal1c1 32328
#define MeowSpriteCGBPal1c2 223
#define MeowSpriteCGBPal1c3 31248

/* Gameboy Color palette 2 */
#define MeowSpriteCGBPal2c0 6076
#define MeowSpriteCGBPal2c1 8935
#define MeowSpriteCGBPal2c2 6596
#define MeowSpriteCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define MeowSpriteCGBPal3c0 6076
#define MeowSpriteCGBPal3c1 8935
#define MeowSpriteCGBPal3c2 6596
#define MeowSpriteCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define MeowSpriteCGBPal4c0 6076
#define MeowSpriteCGBPal4c1 8935
#define MeowSpriteCGBPal4c2 6596
#define MeowSpriteCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define MeowSpriteCGBPal5c0 6076
#define MeowSpriteCGBPal5c1 8935
#define MeowSpriteCGBPal5c2 6596
#define MeowSpriteCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define MeowSpriteCGBPal6c0 6076
#define MeowSpriteCGBPal6c1 8935
#define MeowSpriteCGBPal6c2 6596
#define MeowSpriteCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define MeowSpriteCGBPal7c0 6076
#define MeowSpriteCGBPal7c1 8935
#define MeowSpriteCGBPal7c2 6596
#define MeowSpriteCGBPal7c3 5344
extern const unsigned char MeowSpriteTLE0[];

#endif

/* End of MEOWSPRITE.H */
